version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: advert_user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: advert
    volumes:
    #   - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-init.sql
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5